<a href="https://colab.research.google.com/github/bforoura/IDS/blob/main/Chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chapter 3: Analysis Techniques**

![image.png]()

### **Descriptive Analytics**

* What is happening now based on incoming data? 

* It is a method for quantitatively describing the main features of a collection of data. 

* Typically, it is the ﬁrst kind of data analysis performed on a dataset.

* Usually it is applied to large volumes of data, such as census data.

* Description and interpretation processes are different steps.

* Analysts collect quantitative data or translate qualitative data into numbers using large volumes of raw data that needs to be organized and summarized before it can be analyzed.

**Example**: Census data is a way to describe a population

In [3]:
# pandas is a software library written for the Python programming language for data manipulation and analysis. 
# In particular, it offers data structures and operations for manipulating numerical tables and time series. 

import pandas as pd

In [4]:
pip install censusdata

Collecting censusdata
  Downloading CensusData-1.15.tar.gz (26.6 MB)
     |████████████████████████████████| 26.6 MB 1.6 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from censusdata) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from censusdata) (2.23.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->censusdata) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->censusdata) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->censusdata) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->censusdata) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->censusdata) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->censusdata) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->censusdata) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->censusdata) (2.10)
Building wheels for collected packages: censusdata
  Building wheel for censusdata (setup.py) ... done
  Created wheel for censusdata: filename=CensusData-1.15-py3-none-any.whl size=28205534 sha256=48883ae6e4cd222f3c72e9a9cab5c7b49e3d34d8c465d57cf869c1403f384771
  Stored in directory: /root/.cache/pip/wheels/17/11/8c/933901298f486bd414f2ab1a62a114085f7d7a19dcbda2dd08
Successfully built censusdata
Installing collected packages: censusdata
Successfully installed censusdata-1.15

In [5]:
import censusdata

In [15]:
# Tabulate is an open-source python package/module which is used to print tabular data in nicely formatted tables. 
# It is easy to use and contains a variety of formatting functions.

from tabulate import tabulate

In [16]:
# DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. 
# You can think of it like a spreadsheet or SQL table, or a dict of Series objects. 
# It is generally the most commonly used pandas object.

censusDF = censusdata.download('acs5', 
           2015,
           censusdata.censusgeo([('state', '36'), ('county', '*')]),
           ['B08301_001E', 'B08301_010E'])

* **acs5** refers to the 5 Year American Community Survey and designates the database we are downloading from.
* 2015 is the year that we are getting data from
* censusdata.censusgeo([(**‘state’**, ‘36’), (**‘county’**, ‘*’)]) defines the geography we are interested in. 
* The ‘36’ value is the FIPS (Federal Information Processing Standards) code for New York state while the ‘*’ means we want every county. 
* To look up your own state or county FIPS code refer to the Wikipedia page.
* [‘B08301_001E’, ‘B08301_010E’]  is a list referring to the specific two tables that we are interested in.

In [17]:
# Let's examine the contents of the datafarme in various formats

print(tabulate(censusDF, headers='keys', tablefmt='psql'))

+-------------------------------------------------------------------------+------------------+---------------+
|                                                                         |      B08301_001E |   B08301_010E |
|-------------------------------------------------------------------------+------------------+---------------|
| Schoharie County, New York: Summary level: 050, state:36> county:095    |  13742           |           200 |
| Fulton County, New York: Summary level: 050, state:36> county:035       |  23546           |           141 |
| Rensselaer County, New York: Summary level: 050, state:36> county:083   |  78398           |          1757 |
| Franklin County, New York: Summary level: 050, state:36> county:033     |  19534           |           136 |
| Queens County, New York: Summary level: 050, state:36> county:081       |      1.07675e+06 |        562857 |
| Washington County, New York: Summary level: 050, state:36> county:115   |  27979           |           240 |
| New York County, New York: Summary level: 050, state:36> county:061     | 867298           |        513185 |
| Cayuga County, New York: Summary level: 050, state:36> county:011       |  36043           |           331 |
| Rockland County, New York: Summary level: 050, state:36> county:087     | 142565           |         12292 |
| Niagara County, New York: Summary level: 050, state:36> county:063      |  98802           |          1171 |
| Essex County, New York: Summary level: 050, state:36> county:031        |  17378           |           124 |
| Nassau County, New York: Summary level: 050, state:36> county:059       | 653645           |        106362 |
| Jefferson County, New York: Summary level: 050, state:36> county:045    |  53914           |           199 |
| Suffolk County, New York: Summary level: 050, state:36> county:103      | 721417           |         47169 |
| Wyoming County, New York: Summary level: 050, state:36> county:121      |  18132           |            67 |
| Oswego County, New York: Summary level: 050, state:36> county:075       |  50768           |           402 |
| Wayne County, New York: Summary level: 050, state:36> county:117        |  42277           |           283 |
| Broome County, New York: Summary level: 050, state:36> county:007       |  86839           |          2882 |
| Erie County, New York: Summary level: 050, state:36> county:029         | 431646           |         15964 |
| Sullivan County, New York: Summary level: 050, state:36> county:105     |  31136           |           624 |
| Orange County, New York: Summary level: 050, state:36> county:071       | 171308           |          8807 |
| Schuyler County, New York: Summary level: 050, state:36> county:097     |   7988           |            65 |
| Chenango County, New York: Summary level: 050, state:36> county:017     |  21111           |           138 |
| Bronx County, New York: Summary level: 050, state:36> county:005        | 547961           |        327310 |
| Onondaga County, New York: Summary level: 050, state:36> county:067     | 217113           |          6897 |
| Seneca County, New York: Summary level: 050, state:36> county:099       |  15119           |            79 |
| Putnam County, New York: Summary level: 050, state:36> county:079       |  50308           |          4196 |
| Herkimer County, New York: Summary level: 050, state:36> county:043     |  28326           |           237 |
| Ontario County, New York: Summary level: 050, state:36> county:069      |  52350           |           487 |
| Steuben County, New York: Summary level: 050, state:36> county:101      |  42181           |           284 |
| Hamilton County, New York: Summary level: 050, state:36> county:041     |   1809           |             3 |
| Chautauqua County, New York: Summary level: 050, state:36> county:013   |  56234           |           187 |
| Kings County, New York: Summary level: 050, state:36> county:047        |      1.1422e+06  |        705103 |
| Tioga County, New York: Summary level: 050, state:36> county:107        |  23484           |           124 |
| Orleans County, New York: Summary level: 050, state:36> county:073      |  16790           |           153 |
| Saratoga County, New York: Summary level: 050, state:36> county:091     | 113190           |           969 |
| Columbia County, New York: Summary level: 050, state:36> county:021     |  29219           |           672 |
| Lewis County, New York: Summary level: 050, state:36> county:049        |  11682           |            21 |
| Westchester County, New York: Summary level: 050, state:36> county:119  | 454471           |         98927 |
| Delaware County, New York: Summary level: 050, state:36> county:025     |  19321           |           281 |
| Montgomery County, New York: Summary level: 050, state:36> county:057   |  20913           |           277 |
| Richmond County, New York: Summary level: 050, state:36> county:085     | 205922           |         61319 |
| St. Lawrence County, New York: Summary level: 050, state:36> county:089 |  43703           |           188 |
| Tompkins County, New York: Summary level: 050, state:36> county:109     |  47735           |          2994 |
| Warren County, New York: Summary level: 050, state:36> county:113       |  31161           |           318 |
| Cortland County, New York: Summary level: 050, state:36> county:023     |  23494           |           194 |
| Dutchess County, New York: Summary level: 050, state:36> county:027     | 140195           |          7041 |
| Monroe County, New York: Summary level: 050, state:36> county:055       | 353198           |         10257 |
| Oneida County, New York: Summary level: 050, state:36> county:065       | 101472           |          1132 |
| Ulster County, New York: Summary level: 050, state:36> county:111       |  83332           |          1981 |
| Chemung County, New York: Summary level: 050, state:36> county:015      |  37609           |           769 |
| Livingston County, New York: Summary level: 050, state:36> county:051   |  29457           |           138 |
| Otsego County, New York: Summary level: 050, state:36> county:077       |  27714           |           510 |
| Clinton County, New York: Summary level: 050, state:36> county:019      |  34650           |           211 |
| Greene County, New York: Summary level: 050, state:36> county:039       |  19278           |           182 |
| Albany County, New York: Summary level: 050, state:36> county:001       | 152554           |          8735 |
| Allegany County, New York: Summary level: 050, state:36> county:003     |  19804           |           122 |
| Cattaraugus County, New York: Summary level: 050, state:36> county:009  |  33553           |           166 |
| Madison County, New York: Summary level: 050, state:36> county:053      |  32442           |           120 |
| Schenectady County, New York: Summary level: 050, state:36> county:093  |  72549           |          2909 |
| Genesee County, New York: Summary level: 050, state:36> county:037      |  29146           |           118 |
| Yates County, New York: Summary level: 050, state:36> county:123        |  11127           |            32 |
+-------------------------------------------------------------------------+------------------+---------------+

In [18]:
# Pretty print a data frame in grid format

print(tabulate(censusDF, headers='keys', tablefmt='fancy_grid'))

╒═════════════════════════════════════════════════════════════════════════╤══════════════════╤═══════════════╕
│                                                                         │      B08301_001E │   B08301_010E │
╞═════════════════════════════════════════════════════════════════════════╪══════════════════╪═══════════════╡
│ Schoharie County, New York: Summary level: 050, state:36> county:095    │  13742           │           200 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Fulton County, New York: Summary level: 050, state:36> county:035       │  23546           │           141 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Rensselaer County, New York: Summary level: 050, state:36> county:083   │  78398           │          1757 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Franklin County, New York: Summary level: 050, state:36> county:033     │  19534           │           136 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Queens County, New York: Summary level: 050, state:36> county:081       │      1.07675e+06 │        562857 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Washington County, New York: Summary level: 050, state:36> county:115   │  27979           │           240 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ New York County, New York: Summary level: 050, state:36> county:061     │ 867298           │        513185 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Cayuga County, New York: Summary level: 050, state:36> county:011       │  36043           │           331 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Rockland County, New York: Summary level: 050, state:36> county:087     │ 142565           │         12292 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Niagara County, New York: Summary level: 050, state:36> county:063      │  98802           │          1171 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Essex County, New York: Summary level: 050, state:36> county:031        │  17378           │           124 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Nassau County, New York: Summary level: 050, state:36> county:059       │ 653645           │        106362 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Jefferson County, New York: Summary level: 050, state:36> county:045    │  53914           │           199 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Suffolk County, New York: Summary level: 050, state:36> county:103      │ 721417           │         47169 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Wyoming County, New York: Summary level: 050, state:36> county:121      │  18132           │            67 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Oswego County, New York: Summary level: 050, state:36> county:075       │  50768           │           402 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Wayne County, New York: Summary level: 050, state:36> county:117        │  42277           │           283 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Broome County, New York: Summary level: 050, state:36> county:007       │  86839           │          2882 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Erie County, New York: Summary level: 050, state:36> county:029         │ 431646           │         15964 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Sullivan County, New York: Summary level: 050, state:36> county:105     │  31136           │           624 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Orange County, New York: Summary level: 050, state:36> county:071       │ 171308           │          8807 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Schuyler County, New York: Summary level: 050, state:36> county:097     │   7988           │            65 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Chenango County, New York: Summary level: 050, state:36> county:017     │  21111           │           138 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Bronx County, New York: Summary level: 050, state:36> county:005        │ 547961           │        327310 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Onondaga County, New York: Summary level: 050, state:36> county:067     │ 217113           │          6897 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Seneca County, New York: Summary level: 050, state:36> county:099       │  15119           │            79 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Putnam County, New York: Summary level: 050, state:36> county:079       │  50308           │          4196 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Herkimer County, New York: Summary level: 050, state:36> county:043     │  28326           │           237 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Ontario County, New York: Summary level: 050, state:36> county:069      │  52350           │           487 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Steuben County, New York: Summary level: 050, state:36> county:101      │  42181           │           284 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Hamilton County, New York: Summary level: 050, state:36> county:041     │   1809           │             3 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Chautauqua County, New York: Summary level: 050, state:36> county:013   │  56234           │           187 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Kings County, New York: Summary level: 050, state:36> county:047        │      1.1422e+06  │        705103 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Tioga County, New York: Summary level: 050, state:36> county:107        │  23484           │           124 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Orleans County, New York: Summary level: 050, state:36> county:073      │  16790           │           153 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Saratoga County, New York: Summary level: 050, state:36> county:091     │ 113190           │           969 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Columbia County, New York: Summary level: 050, state:36> county:021     │  29219           │           672 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Lewis County, New York: Summary level: 050, state:36> county:049        │  11682           │            21 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Westchester County, New York: Summary level: 050, state:36> county:119  │ 454471           │         98927 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Delaware County, New York: Summary level: 050, state:36> county:025     │  19321           │           281 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Montgomery County, New York: Summary level: 050, state:36> county:057   │  20913           │           277 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Richmond County, New York: Summary level: 050, state:36> county:085     │ 205922           │         61319 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ St. Lawrence County, New York: Summary level: 050, state:36> county:089 │  43703           │           188 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Tompkins County, New York: Summary level: 050, state:36> county:109     │  47735           │          2994 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Warren County, New York: Summary level: 050, state:36> county:113       │  31161           │           318 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Cortland County, New York: Summary level: 050, state:36> county:023     │  23494           │           194 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Dutchess County, New York: Summary level: 050, state:36> county:027     │ 140195           │          7041 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Monroe County, New York: Summary level: 050, state:36> county:055       │ 353198           │         10257 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Oneida County, New York: Summary level: 050, state:36> county:065       │ 101472           │          1132 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Ulster County, New York: Summary level: 050, state:36> county:111       │  83332           │          1981 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Chemung County, New York: Summary level: 050, state:36> county:015      │  37609           │           769 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Livingston County, New York: Summary level: 050, state:36> county:051   │  29457           │           138 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Otsego County, New York: Summary level: 050, state:36> county:077       │  27714           │           510 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Clinton County, New York: Summary level: 050, state:36> county:019      │  34650           │           211 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Greene County, New York: Summary level: 050, state:36> county:039       │  19278           │           182 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Albany County, New York: Summary level: 050, state:36> county:001       │ 152554           │          8735 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Allegany County, New York: Summary level: 050, state:36> county:003     │  19804           │           122 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Cattaraugus County, New York: Summary level: 050, state:36> county:009  │  33553           │           166 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Madison County, New York: Summary level: 050, state:36> county:053      │  32442           │           120 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Schenectady County, New York: Summary level: 050, state:36> county:093  │  72549           │          2909 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Genesee County, New York: Summary level: 050, state:36> county:037      │  29146           │           118 │
├─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────┤
│ Yates County, New York: Summary level: 050, state:36> county:123        │  11127           │            32 │
╘═════════════════════════════════════════════════════════════════════════╧══════════════════╧═══════════════╛

In [20]:
# Another example of creating a data frame from a dictionary and printing it

usersDF = pd.DataFrame({
                 'username' :   ['Jack','Jill','Pam','Sam'],
                 'passwd':      [1111, 2222, 3333, 4444],
                 'dept':        ['CSC','MAT','DSS','ART']})
# Display the Dataframe
print(usersDF)

  username  passwd dept
0     Jack    1111  CSC
1     Jill    2222  MAT
2      Pam    3333  DSS
3      Sam    4444  ART

In [21]:
print(tabulate(usersDF, headers='keys', tablefmt='fancy_grid'))

╒════╤════════════╤══════════╤════════╕
│    │ username   │   passwd │ dept   │
╞════╪════════════╪══════════╪════════╡
│  0 │ Jack       │     1111 │ CSC    │
├────┼────────────┼──────────┼────────┤
│  1 │ Jill       │     2222 │ MAT    │
├────┼────────────┼──────────┼────────┤
│  2 │ Pam        │     3333 │ DSS    │
├────┼────────────┼──────────┼────────┤
│  3 │ Sam        │     4444 │ ART    │
╘════╧════════════╧══════════╧════════╛

# Let's prepare to import a data table from MySQL

In [22]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.28-cp37-cp37m-manylinux1_x86_64.whl (37.6 MB)
     |████████████████████████████████| 37.6 MB 1.2 MB/s
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mysql-connector-python) (3.17.3)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.7/dist-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.0.28

In [23]:
import mysql.connector as sql

In [24]:
# use the same credentials you use to connect to MySQL via Workbench

db_connection = sql.connect(host='208.109.18.154', database='ids1db', user='ids1', password='')
db_cursor = db_connection.cursor()
db_cursor.execute('SELECT * FROM chickwts')

table_rows = db_cursor.fetchall()

chickDF = pd.DataFrame(table_rows)

print(tabulate(chickDF, headers='keys', tablefmt='fancy_grid'))

╒════╤═════╤═════╤═══════════╕
│    │   0 │   1 │ 2         │
╞════╪═════╪═════╪═══════════╡
│  0 │   1 │ 179 │ horsebean │
├────┼─────┼─────┼───────────┤
│  1 │   2 │ 160 │ horsebean │
├────┼─────┼─────┼───────────┤
│  2 │   3 │ 136 │ horsebean │
├────┼─────┼─────┼───────────┤
│  3 │   4 │ 227 │ horsebean │
├────┼─────┼─────┼───────────┤
│  4 │   5 │ 217 │ horsebean │
├────┼─────┼─────┼───────────┤
│  5 │   6 │ 168 │ horsebean │
├────┼─────┼─────┼───────────┤
│  6 │   7 │ 108 │ horsebean │
├────┼─────┼─────┼───────────┤
│  7 │   8 │ 124 │ horsebean │
├────┼─────┼─────┼───────────┤
│  8 │   9 │ 143 │ horsebean │
├────┼─────┼─────┼───────────┤
│  9 │  10 │ 140 │ horsebean │
├────┼─────┼─────┼───────────┤
│ 10 │  11 │ 309 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 11 │  12 │ 229 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 12 │  13 │ 181 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 13 │  14 │ 141 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 14 │  15 │ 260 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 15 │  16 │ 203 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 16 │  17 │ 148 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 17 │  18 │ 169 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 18 │  19 │ 213 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 19 │  20 │ 257 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 20 │  21 │ 244 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 21 │  22 │ 271 │ linseed   │
├────┼─────┼─────┼───────────┤
│ 22 │  23 │ 243 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 23 │  24 │ 230 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 24 │  25 │ 248 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 25 │  26 │ 327 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 26 │  27 │ 329 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 27 │  28 │ 250 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 28 │  29 │ 193 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 29 │  30 │ 271 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 30 │  31 │ 316 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 31 │  32 │ 267 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 32 │  33 │ 199 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 33 │  34 │ 171 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 34 │  35 │ 158 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 35 │  36 │ 248 │ soybean   │
├────┼─────┼─────┼───────────┤
│ 36 │  37 │ 423 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 37 │  38 │ 340 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 38 │  39 │ 392 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 39 │  40 │ 339 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 40 │  41 │ 341 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 41 │  42 │ 226 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 42 │  43 │ 320 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 43 │  44 │ 295 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 44 │  45 │ 334 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 45 │  46 │ 322 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 46 │  47 │ 297 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 47 │  48 │ 318 │ sunflower │
├────┼─────┼─────┼───────────┤
│ 48 │  49 │ 325 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 49 │  50 │ 257 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 50 │  51 │ 303 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 51 │  52 │ 315 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 52 │  53 │ 380 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 53 │  54 │ 153 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 54 │  55 │ 263 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 55 │  56 │ 242 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 56 │  57 │ 206 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 57 │  58 │ 344 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 58 │  59 │ 258 │ meatmeal  │
├────┼─────┼─────┼───────────┤
│ 59 │  60 │ 368 │ casein    │
├────┼─────┼─────┼───────────┤
│ 60 │  61 │ 390 │ casein    │
├────┼─────┼─────┼───────────┤
│ 61 │  62 │ 379 │ casein    │
├────┼─────┼─────┼───────────┤
│ 62 │  63 │ 260 │ casein    │
├────┼─────┼─────┼───────────┤
│ 63 │  64 │ 404 │ casein    │
├────┼─────┼─────┼───────────┤
│ 64 │  65 │ 318 │ casein    │
├────┼─────┼─────┼───────────┤
│ 65 │  66 │ 352 │ casein    │
├────┼─────┼─────┼───────────┤
│ 66 │  67 │ 359 │ casein    │
├────┼─────┼─────┼───────────┤
│ 67 │  68 │ 216 │ casein    │
├────┼─────┼─────┼───────────┤
│ 68 │  69 │ 222 │ casein    │
├────┼─────┼─────┼───────────┤
│ 69 │  70 │ 283 │ casein    │
├────┼─────┼─────┼───────────┤
│ 70 │  71 │ 332 │ casein    │
╘════╧═════╧═════╧═══════════╛

In [26]:
# get some information about the columns in the dataframe
chickDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       71 non-null     int64
 1   1       71 non-null     int64
 2   2       71 non-null     object
dtypes: int64(2), object(1)
memory usage: 1.8+ KB

In [32]:
# display the first 10 rows
chickDF.head(10)

    0    1          2
0   1  179  horsebean
1   2  160  horsebean
2   3  136  horsebean
3   4  227  horsebean
4   5  217  horsebean
5   6  168  horsebean
6   7  108  horsebean
7   8  124  horsebean
8   9  143  horsebean
9  10  140  horsebean

In [44]:
# Let’s find out what categories exist in column 2 and how many districts belong to it by using the value_counts() method

chickDF[2].value_counts()

soybean      14
linseed      12
sunflower    12
casein       12
meatmeal     11
horsebean    10
Name: 2, dtype: int64

In [45]:
# Let's find the min of the weights column

chickDF[1].min()

108

In [42]:
# Let's create a new dataframe and summarize the wieghts column with a few statistical moments

chickSummaryDF = pd.DataFrame({
                 'Min' :   [chickDF[1].min()],
                 'Max':    [chickDF[1].max()],
                 'Mean':   [chickDF[1].mean()],
                 'STD':    [chickDF[1].std()],
                 'Var':    [chickDF[1].var()], 
                 })

# Display the Summary Dataframe
print(tabulate(chickSummaryDF, headers='keys', tablefmt='fancy_grid'))

╒════╤═══════╤═══════╤════════╤═════════╤════════╕
│    │   Min │   Max │   Mean │     STD │    Var │
╞════╪═══════╪═══════╪════════╪═════════╪════════╡
│  0 │   108 │   423 │ 261.31 │ 78.0737 │ 6095.5 │
╘════╧═══════╧═══════╧════════╧═════════╧════════╛

**References**
* https://towardsdatascience.com/mapping-us-census-data-with-python-607df3de4b9c
* https://thispointer.com/pretty-print-a-pandas-dataframe/#psql-format
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html